# PYTORCH

<img src= 'https://miro.medium.com/max/880/1*WbLIc4-xIOfHiO2oWzimyA.png' width=500/>

In [1]:
import torch

import numpy as np

# if GPU(cuda) is available use it or else use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
print(device)

cuda


In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device)

# Tensor attributes

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [5]:
print(my_tensor.dtype)

torch.float32


In [6]:
print(my_tensor.device)

cuda:0


In [7]:
print(my_tensor.shape)
# print(my_tensor.retains_grad)

torch.Size([2, 3])


# Other common initialization methods

In [8]:
# random values not only zero (uninitialized)
x = torch.empty(size=(3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# zeros tensor
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# random values
x = torch.rand((3, 3))
print(x)

tensor([[0.9396, 0.4675, 0.5218],
        [0.7798, 0.3643, 0.9267],
        [0.6757, 0.2614, 0.7398]])


In [11]:
# all ones
x = torch.ones((3, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
# identity matrix
x = torch.eye(3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
# or we can use
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
x = torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [15]:
x = torch.arange(9)
x_33 = x.reshape(3,3)
x_33

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
x = torch.arange(start=0, end=10, step=1.1)
print(x)

tensor([0.0000, 1.1000, 2.2000, 3.3000, 4.4000, 5.5000, 6.6000, 7.7000, 8.8000,
        9.9000])


In [17]:
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [18]:
# normal distributed
x = torch.empty((1, 5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.2696,  0.4472,  0.2642, -0.3589, -0.3563]])


In [19]:
# uniform distribution
x = torch.empty((1,5)).uniform_(0,1)
print(x)

tensor([[0.7282, 0.0934, 0.2367, 0.3887, 0.4895]])


# Convert tensors from one type to another

In [20]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [21]:
# change them to type bool
tensor.bool()

tensor([False,  True,  True,  True])

In [22]:
# int16
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [23]:
# int64
tensor.long()

tensor([0, 1, 2, 3])

In [24]:
# float16
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [25]:
# float32
tensor.float()

tensor([0., 1., 2., 3.])

In [26]:
# float64
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

# Numpy array to Tensor

In [27]:
np_array = np.array([[1,2,3], [4,5,6]])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [29]:
# to get np_array back from tensor
np_array_back = tensor.numpy()
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

# Tensor math & comparision operators

In [30]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [31]:
# add
z = torch.add(x,y)
z

tensor([5, 7, 9])

In [32]:
# or we can use
z = x + y
z

tensor([5, 7, 9])

In [33]:
# subtractabs
z = x - y
z

tensor([-3, -3, -3])

In [34]:
# division 
z = torch.true_divide(x, y)
z

tensor([0.2500, 0.4000, 0.5000])

## Inplace operations

In [35]:
# inplace op's are used when we don't want to create another variable
t = torch.rand(3)
t

tensor([0.1245, 0.2446, 0.9012])

In [36]:
#inplace addition
t.add_(x)

tensor([1.1245, 2.2446, 3.9012])

In [37]:
# or use
t += x
t

tensor([2.1245, 4.2446, 6.9012])

In [38]:
# exponentiation element wise
# z = x.pow(2)
z = x**2
z

tensor([1, 4, 9])

In [39]:
# comparision
z = x>0
z

tensor([True, True, True])

In [40]:
z = x<0
z

tensor([False, False, False])

In [41]:
z.ndimension()

1

In [42]:
z.numel()

3

## Matrix multiplication

In [43]:
x1 = torch.rand((3,5))
x2 = torch.rand((5,2))

In [44]:
x1

tensor([[0.4885, 0.5602, 0.1821, 0.8378, 0.4549],
        [0.9817, 0.1293, 0.7340, 0.2408, 0.8649],
        [0.3109, 0.1089, 0.5132, 0.1219, 0.8087]])

In [45]:
x2

tensor([[0.7422, 0.5717],
        [0.2140, 0.4516],
        [0.3124, 0.9656],
        [0.3467, 0.8931],
        [0.8765, 0.5565]])

In [46]:
x3 = torch.mm(x1, x2)
x3

tensor([[1.2286, 1.7095],
        [1.8272, 2.0248],
        [1.1655, 1.2813]])

In [47]:
x3 = x1.mm(x2)
x3

tensor([[1.2286, 1.7095],
        [1.8272, 2.0248],
        [1.1655, 1.2813]])

In [48]:
# matrix exponentiation

matrix_exp = torch.ones((5,5))

# (matrix_exp).mm((matrix_exp).mm(matrix_exp))
matrix_exp.matrix_power(3)

tensor([[25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.]])

In [49]:
# element wise multiplication
z = x * y
z

tensor([ 4, 10, 18])

In [50]:
# dot product =  sum (element wise multiplication)
z =  torch.dot(x, y)
z

tensor(32)

## Batch matrix multiplication

In [51]:
batch = 32
n = 10
m = 20
p = 30

In [52]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m ,p))

In [53]:
out_bmm = torch.bmm(tensor1, tensor2) # batch,n,p

# Broadcasting

In [54]:
x1 = torch.rand((5,5))
x2 = torch.rand((5,1))

# x2 is a column vector, it's broadcasted to the shape of x1
# ==> x2 = [x2, x2, x2, x2, x2]
z = x1 - x2
z

tensor([[-0.6131, -0.4426, -0.6187, -0.3248, -0.9416],
        [-0.4181, -0.1684,  0.1891, -0.4086,  0.2783],
        [ 0.0140, -0.4488, -0.1368, -0.1389, -0.6542],
        [-0.5919, -0.6611,  0.1339, -0.5112, -0.4803],
        [ 0.5561,  0.0773,  0.2776,  0.6071,  0.6325]])

In [55]:
z = x1 ** x2
z

tensor([[0.3857, 0.5561, 0.3801, 0.6738, 0.0568],
        [0.3410, 0.5942, 0.8542, 0.3530, 0.9100],
        [0.7902, 0.3805, 0.6693, 0.6675, 0.1162],
        [0.3051, 0.2300, 0.9716, 0.3883, 0.4192],
        [0.9476, 0.7920, 0.8745, 0.9583, 0.9634]])

# other useful tensor operations

In [56]:
x = torch.tensor([[1,2,4],[8,5,6],[7,8,9]])
x

tensor([[1, 2, 4],
        [8, 5, 6],
        [7, 8, 9]])

In [57]:
column_sum = torch.sum(x, dim=0)
column_sum

tensor([16, 15, 19])

In [58]:
row_sum = torch.sum(x, dim=1)
row_sum

tensor([ 7, 19, 24])

In [59]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor([8, 8, 9]), tensor([1, 2, 2]))

In [60]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor([1, 2, 4]), tensor([0, 0, 0]))

In [61]:
x = torch.linspace(-3, 1, 10)
x

tensor([-3.0000, -2.5556, -2.1111, -1.6667, -1.2222, -0.7778, -0.3333,  0.1111,
         0.5556,  1.0000])

In [62]:
abs_x = torch.abs(x)
abs_x

tensor([3.0000, 2.5556, 2.1111, 1.6667, 1.2222, 0.7778, 0.3333, 0.1111, 0.5556,
        1.0000])

In [63]:
z = torch.argmax(x, dim=0)
z

tensor(9)

In [64]:
z = torch.argmin(x, dim=0)
z

tensor(0)

In [65]:
# mean requires data to be of type float
mean_x = torch.mean(x.float())
mean_x

tensor(-1.)

In [66]:
# sorting
y = torch.rand((5,1))
y

tensor([[0.4957],
        [0.4903],
        [0.1372],
        [0.4224],
        [0.0210]])

In [67]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
sorted_y, indices

(tensor([[0.0210],
         [0.1372],
         [0.4224],
         [0.4903],
         [0.4957]]),
 tensor([[4],
         [2],
         [3],
         [1],
         [0]]))

In [68]:
tensor = torch.tensor([-1,-2,-5,0,1,4,3,6,10,19])

In [69]:
# anything < 0 becomes 0 and > 5 becomes 5
tensor = torch.clamp(tensor, min=0, max=5)
tensor

tensor([0, 0, 0, 0, 1, 4, 3, 5, 5, 5])

# any & all


In [70]:
# indicates true or false
x = torch.tensor([1,0,1,1,0], dtype=torch.bool)

In [71]:
# returns true if any one is true
z = torch.any(x)
z

tensor(True)

In [72]:
# returns true only if all are true
z = torch.all(x)
z

tensor(False)

# Concatenation

In [73]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

In [74]:
# concatenation
torch.cat((x1, x2), dim=0).shape

torch.Size([4, 5])

In [75]:
torch.cat((x1, x2), dim=1).shape

torch.Size([2, 10])

In [76]:
# flatten
z = x1.view(-1)
z

tensor([0.3571, 0.2181, 0.8800, 0.9664, 0.3417, 0.7617, 0.1713, 0.4226, 0.6423,
        0.7085])

In [77]:
batch = 64
x = torch.rand((batch, 2, 5))

In [78]:
# we need batch to remain same but change 2, 5 to flatten
z = x.view((batch, -1))

In [79]:
#we need batch to remain same but change 2, 5 to 5, 2

# dim 0 stays in place
# dim 1 now has 2
# dim 2 now has 1
print(z.shape)
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 10])
torch.Size([64, 5, 2])


In [80]:
x = torch.arange(10)